### ISSUE TITLE
Missing "vendor/lineage", aborting

### ISSUE THREAD

**Issue by Eyap53** [lineageos4microg/docker-lineage-cicd#221]
Same issue as #120 .

Trying to build for an unsupported device (on lineage-18.1) produced the error : 'Missing "vendor/lineage", aborting'.
Trying to build for the same device but on a supported branch (17.1) worked.

Tested on both Linux and windows. On Windows, tested with/without admins permissions. On Linux, tested with/without sudo, and with docker part of the user groups.

---- 
I provide the files for completeness, but I believe there isn't anything out of the ordinary : 

ginkgo.xml : 
```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="ginkgo-dev/android_device_xiaomi_ginkgo" path="device/xiaomi/ginkgo" remote="github" />
  <project name="ginkgo-dev/android_kernel_xiaomi_ginkgo" path="kernel/xiaomi/ginkgo" remote="github" />
  <project name="ginkgo-dev/android_vendor_xiaomi_ginkgo" path="vendor/xiaomi/ginkgo" remote="github" />
  <project name="ginkgo-dev/android_hardware_qcom_display" path="hardware/qcom-caf/sm8150/display" remote="github" />
</manifest>
```

custom_packages.xml : 
```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="ginkgo-dev/android_prebuilts_clang_host_linux-x86_clang-sdllvm" path="prebuilts/clang/host/linux-x86/clang-sdllvm" remote="github" />
</manifest>
```

and finally the docker compose : 
```
version: '3.3'
services:
    docker-lineage-cicd:
        environment:
            - BRANCH_NAME=lineage-18.1
            - DEVICE_LIST=ginkgo
            - SIGN_BUILDS=true
            - SIGNATURE_SPOOFING=restricted
            - 'CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension'
            - INCLUDE_PROPRIETARY=false
        volumes:
            - './lineage:/srv/src'
            - './zips:/srv/zips'
            - './logs:/srv/logs'
            - './cache:/srv/ccache'
            - './keys:/srv/keys'
            - './manifests:/srv/local_manifests'
        image: lineageos4microg/docker-lineage-cicd
```

Any idea ?
