### ISSUE TITLE
lemonadep 21 build error can't read vendor/lineage/config/common.mk

### ISSUE THREAD

**Issue by gwstorm** [lineageos4microg/docker-lineage-cicd#699]
Moving from [this issue](https://github.com/lineageos4microg/docker-lineage-cicd/issues/689#issuecomment-2425591261) since mine is different. 

I attempted a build today and was getting failed results. After searching around and not seeing anything directly related, I cleared my src directory and removed all previously used volumes to try and start from scratch as that has helped in the past. Since doing that, the build now fails virtually immediately with only a repo log stating the repo was initialized. 

Docker output is as follows - 

```
 ✔ Container lineage-docker-lineage-cicd-1  Created                                                                                                                                                                                                                                  0.1s
Attaching to docker-lineage-cicd-1
docker-lineage-cicd-1  | Set cache size limit to 50.0 GB
docker-lineage-cicd-1  | >> [Mon Oct 21 07:53:06 UTC 2024] Branch:  lineage-21.0
docker-lineage-cicd-1  | >> [Mon Oct 21 07:53:06 UTC 2024] Devices: lemonadep
docker-lineage-cicd-1  | >> [Mon Oct 21 07:53:06 UTC 2024] Copying '/srv/local_manifests/*.xml' to '.repo/local_manifests/'
docker-lineage-cicd-1  | >> [Mon Oct 21 07:53:07 UTC 2024] (Re)initializing branch repository
docker-lineage-cicd-1  | sed: can't read vendor/lineage/config/common.mk: No such file or directory
docker-lineage-cicd-1 exited with code 2
```

Docker compose file  - 

```
services:
    docker-lineage-cicd:
        environment:
            - BRANCH_NAME=lineage-21.0
            - DEVICE_LIST=lemonadep
            - SIGN_BUILDS=true
            - WITH_GMS=true
            - OTA_URL=redacted
            - DELETE_OLD_ZIPS=2
            - PARALLEL_JOBS=12
            - CCACHE_SIZE=50G
        volumes:
            - '/mnt/cache/lineage/src:/srv/src'
            - '/mnt/cache/lineage/zips:/srv/zips'
            - '/mnt/cache/lineage/logs:/srv/logs'
            - '/tmp/ccache:/srv/ccache'
            - '/mnt/cache/lineage/keys:/srv/keys'
            - '/mnt/cache/lineage/local_manifests:/srv/local_manifests'
        image: lineageos4microg/docker-lineage-cicd
```
